#!/bin/sh
#
# This is a package manager agnostic helper to upgrade package(s).
#

set -e # Exit immediately if a command exits with a non-zero status.

usage() {
    echo "usage: $(basename "$0") [PKG...]" >&2
    exit 1
}

die() {
    echo "ERROR: $*" >&2
    exit 1
}

trap : TERM QUIT INT
trap "cleanup" EXIT

#
# APK functions
#

upgrade_pkg_apk() {
    apk --no-cache --logfile=no upgrade "$@"
}

cleanup_apk() {
    find /etc -name "*.apk-new" -delete
    rm -rf \
        /var/cache/misc/* \
        /var/log/apk.log \

}

#
# APT functions
#

upgrade_pkg_apt() {
    mkdir -p /tmp/apt_cache
    apt-get -q update
    if [ -n "$1" ]; then
        apt-get -q install -y --no-install-recommends --only-upgrade "$@"
    else
        apt-get -q upgrade -y
    fi
    apt-get -q autoremove -y --purge
}

cleanup_apt() {
    apt-get -q clean
    rm -rf \
        /tmp/apt_cache \
        /var/lib/apt/lists/* \
        /var/log/dpkg.log \
        /var/log/alternatives.log \
        /var/log/apt/*
}

#
# Package manager agnostic functions
#

upgrade_pkg() {
    if command -v apk > /dev/null; then
        upgrade_pkg_apk "$@"
    else
        upgrade_pkg_apt "$@"
    fi
}

cleanup() {
    if command -v apk > /dev/null; then
        cleanup_apk
    else
        cleanup_apt
    fi
}

#
# Main
#

if command -v apt > /dev/null; then
    export DEBIAN_FRONTEND=noninteractive
    export LC_ALL=C
fi

if [ $# -eq 1 ] && [ "${1}" = "all" ]; then
    shift
fi
upgrade_pkg "$@"

# vim:ft=sh:ts=4:sw=4:et:sts=4
