#!/bin/sh
#
# Clear the /tmp directory.
#

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

# Remove everything, except:
#   - /tmp/.cont-env-internal: this file has been generated by the init script.
find /tmp -mindepth 1 -maxdepth 1 ! -name '.cont-env-internal' -exec rm -rf {} +

# Clear `/run`, but ignore errors, because container engines can mount files
# under `/run` that will fail to be removed (e.g. secrets or .containerenv from
# podman).
find /run -mindepth 1 -maxdepth 1 -exec rm -rf {} + 2>/dev/null || true

# vim:ft=sh:ts=4:sw=4:et:sts=4
